### ISSUE TITLE
can't work for Scratch2?

### ISSUE THREAD

**Issue by VivianSnow** [ucsb-cs-education/hairball#9]
Hi Bryce,
I find this project recently by your paper _Hairball: Lint-inspired Static Analysis of Scratch Projects_, but unfortunately I find that hairball can't work for scratch2 project. I try to install hairball by pip or source code, but i get same error return when I run hairball

```python
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/hairball/__init__.py", line 226, in process
    scratch = self.cache.load(filename)
  File "build/bdist.linux-x86_64/egg/hairball/__init__.py", line 89, in load
    cPickle.dump(scratch, fp, cPickle.HIGHEST_PROTOCOL)
PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```

I searched this error return at google and stackoverflow, but got nothing. I have no experience of Cpickle and appdirs, so I have a glance at source code, and try to use `--no-cache` option,  error disappeared but program output nothing(I have tryed all the plugins).I also found a Scrath1.4 project file named `tmp.sb` in souce code, I tested it and all work perfectly.

My test environment are belows

```
OS: Ubuntu 16.04
python: Python 2.7.12
venv freeze:
  appdirs==1.4.3
  construct==2.0.6
  hairball==0.3
  kurt==2.0.6
  olefile==0.44
  Pillow==4.2.1
```

Thanks a lot.

**Comment by VivianSnow** [comment]
@bboe

**Comment by bboe** [comment]
Hi @VivianSnow. Unfortunately I am no longer supporting this work as I am out of academia. Perhaps, @jemole has some insight as to what's going on.

**Comment by jemole** [comment]
Hi @VivianSnow,

Hairball works fine with Scratch 2 projects. In fact, Hairball is used in Dr. Scratch (http://drscratch.org) to analyze both Scratch 1.4 and 2.0 projects. 

Perhaps you could try to analyze that project in Dr. Scratch and see if it works. If that is the case, we could try to find out what is going on in your installation for causing that problem.

**Comment by bboe** [comment]
Closing this issue due to lack of inactivity. @VivianSnow if you're still getting issues, feel free to reopen with more details.

**Comment by simonrose121** [comment]
If anyone else stumbles across this issue as I did, it can be fixed by using the -C flag when running hairball to not use the cache. This fixed the problem for me when analysing Scratch 2 projects.

**Comment by timozandonella** [comment]
@simonrose121 +1
